"""Small bounded GF(256) erasure primitive for prospective parity shards.

The systematic data shards are evaluated at distinct nonzero field elements;
parity row j uses the j-th power of each data-shard element. Any r missing
data shards can be solved using the first r parity rows, provided all those
independently retained parity shards are intact. This module proves no file
ownership or capture provenance; callers must verify their own manifests and
coordinate hashes before publishing bytes.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence

import numpy as np


MAX_DATA_SHARDS = 16
MAX_PARITY_SHARDS = 4
MAX_SHARD_BYTES = 1 << 20


def _field_tables() -> tuple[tuple[int, ...], tuple[int, ...], np.ndarray]:
    exp = [0] * 512
    log = [0] * 256
    value = 1
    for power in range(255):
        exp[power] = value
        log[value] = power
        value <<= 1
        if value & 0x100:
            value ^= 0x11D
    exp[255:] = exp[:257]
    product = np.empty((256, 256), dtype="u1")
    product[0] = 0
    for coefficient in range(1, 256):
        product[coefficient, 0] = 0
        for byte in range(1, 256):
            product[coefficient, byte] = exp[log[coefficient] + log[byte]]
    return tuple(exp), tuple(log), product


_EXP, _LOG, _PRODUCT = _field_tables()


def _multiply(left: int, right: int) -> int:
    return int(_PRODUCT[left, right])


def _inverse(value: int) -> int:
    if not value:
        raise ValueError("singular erasure coefficient matrix")
    return _EXP[255 - _LOG[value]]


def _coefficient(index: int, row: int) -> int:
    value = index + 1
    result = 1
    for _ in range(row):
        result = _multiply(result, value)
    return result


def _check_payloads(payloads: Sequence[bytes], parity_count: int) -> int:
    if type(parity_count) is not int or not 1 <= parity_count <= MAX_PARITY_SHARDS:
        raise ValueError("parity count must be 1 through 4")
    if not 1 <= len(payloads) <= MAX_DATA_SHARDS:
        raise ValueError("data shard count must be 1 through 16")
    size = len(payloads[0])
    if not 1 <= size <= MAX_SHARD_BYTES or any(type(x) is not bytes or len(x) != size for x in payloads):
        raise ValueError("data shards must have one bounded equal byte length")
    return size


def encode_parity(payloads: Sequence[bytes], parity_count: int) -> tuple[bytes, ...]:
    """Encode one to four independent parity shards for equal-sized data."""
    size = _check_payloads(payloads, parity_count)
    shards = [np.zeros(size, dtype="u1") for _ in range(parity_count)]
    for index, payload in enumerate(payloads):
        raw = np.frombuffer(payload, dtype="u1")
        for row, target in enumerate(shards):
            target ^= _PRODUCT[_coefficient(index, row), raw]
    return tuple(bytes(shard) for shard in shards)


def _inverse_matrix(matrix: list[list[int]]) -> list[list[int]]:
    size = len(matrix)
    augmented = [row[:] + [int(column == index) for column in range(size)]
                 for index, row in enumerate(matrix)]
    for column in range(size):
        pivot = next((row for row in range(column, size) if augmented[row][column]), None)
        if pivot is None:
            raise ValueError("singular erasure coefficient matrix")
        augmented[column], augmented[pivot] = augmented[pivot], augmented[column]
        factor = _inverse(augmented[column][column])
        augmented[column] = [_multiply(value, factor) for value in augmented[column]]
        for row in range(size):
            if row == column:
                continue
            factor = augmented[row][column]
            if factor:
                augmented[row] = [left ^ _multiply(factor, right)
                                  for left, right in zip(augmented[row], augmented[column])]
    return [row[size:] for row in augmented]


def recover_data(
    data_count: int, known: Mapping[int, bytes], parity: Sequence[bytes],
) -> dict[int, bytes]:
    """Return missing data shards when at most m data shards are absent.

    `parity` contains the first m parity rows generated by `encode_parity`.
    The caller independently verifies each result against a prior coordinate
    hash. This primitive does not know which currently stored bytes are bad.
    """
    if type(data_count) is not int or not 1 <= data_count <= MAX_DATA_SHARDS:
        raise ValueError("invalid data shard count")
    if not 1 <= len(parity) <= MAX_PARITY_SHARDS:
        raise ValueError("invalid parity shard count")
    length = len(parity[0])
    if (not 1 <= length <= MAX_SHARD_BYTES
            or any(type(item) is not bytes or len(item) != length for item in parity)
            or any(type(index) is not int or not 0 <= index < data_count
                   or type(payload) is not bytes or len(payload) != length
                   for index, payload in known.items())):
        raise ValueError("invalid erasure shard extent or index")
    missing = [index for index in range(data_count) if index not in known]
    count = len(missing)
    if count > len(parity):
        raise ValueError("more missing data shards than available parity")
    if not count:
        return {}
    matrix = [[_coefficient(index, row) for index in missing] for row in range(count)]
    inverse = _inverse_matrix(matrix)
    residuals = []
    for row in range(count):
        residual = np.frombuffer(parity[row], dtype="u1").copy()
        for index, payload in known.items():
            residual ^= _PRODUCT[_coefficient(index, row), np.frombuffer(payload, dtype="u1")]
        residuals.append(residual)
    result = {}
    for position, index in enumerate(missing):
        shard = np.zeros(length, dtype="u1")
        for row in range(count):
            shard ^= _PRODUCT[inverse[position][row], residuals[row]]
        result[index] = bytes(shard)
    return result
